#!/bin/sh

umask 077

TMP_PATH=/tmp/pd.key.
PERSON=${TMP_PATH}personi.$$
OFFICE=${TMP_PATH}office.$$
TELEPHONE=${TMP_PATH}telephone.$$
USER=${TMP_PATH}user.$$

trap "exit 1" HUP INT PIPE QUIT TERM
trap "rm -f $PERSON $OFFICE $TELEPHONE $USER" EXIT

awk -F: '{ print $1":"$5 }' > $USER

sed -e 's=/.*==' -e 's=^\([^:]*\):\(.*\) \([^ ]*\)=\1:\3, \2=' < $USER | sort > $PERSON

sed -e 's=^\([^:]*\)[^/]*/\([^/]*\)/.*$=\1:\2=' < $USER | sort > $OFFICE

sed -e 's=^\([^:]*\)[^/]*/[^/]*/\(.*\)=\1:\2=' < $USER | sort > $TELEPHONE

join -t: $PERSON $OFFICE |
    join -t: - $TELEPHONE |
        cut -d: -f2- |
            sort -t: -k1,1 -k2,2 -k3,3 |
               awk -F: '{ printf("%-39s\t%s\t%s\n", $1, $2, $3) }' 
